# Generated by Django 3.0.1 on 2022-11-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='s_financiero',
            fields=[
                ('idEjecutivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEjecutivo', models.CharField(max_length=50)),
                ('apellidoEjecutivo', models.CharField(max_length=50)),
            ],
        ),
    ]
