# Generated by Django 3.0.1 on 2022-11-02 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registroAsociado', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='s_financiero',
            new_name='ejecutivo',
        ),
    ]
