# Generated by Django 3.0.1 on 2022-11-02 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registroAsociado', '0002_auto_20221102_0506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejecutivo',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='ejecutivo',
            table='ejecutivo',
        ),
        migrations.CreateModel(
            name='asociacion',
            fields=[
                ('idAsociado', models.AutoField(primary_key=True, serialize=False)),
                ('fechaAsociacion', models.CharField(max_length=50)),
                ('lugarAsociacion', models.CharField(max_length=100)),
                ('ejecutivo_idEjecutivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroAsociado.ejecutivo')),
            ],
            options={
                'db_table': 'asociacion',
                'managed': True,
            },
        ),
    ]
