# Generated by Django 4.1 on 2022-11-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroAsociado', '0004_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoActEconomica',
            fields=[
                ('idTipoActEconomica', models.AutoField(primary_key=True, serialize=False)),
                ('nombreActEconomica', models.CharField(max_length=50)),
                ('rubroActEconomica', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipoActEconomica',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tipoDocumento',
            fields=[
                ('idTipoDocumento', models.AutoField(primary_key=True, serialize=False)),
                ('nombreDocumento', models.CharField(choices=[('DUI', 'DUI'), ('NIT', 'NIT'), ('PARTI', 'PARTIDA DE NACIMIENTO'), ('PASAP', 'PASAPORTE'), ('CARNE', 'CARNE DE RESIDENCIA')], default='DUI', max_length=5)),
            ],
            options={
                'db_table': 'tipoDocumento',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombreGenero',
            field=models.CharField(choices=[('H', 'HOMBRE'), ('M', 'MUJER')], max_length=1),
        ),
        migrations.AlterModelTable(
            name='genero',
            table='genero',
        ),
    ]
