# Generated by Django 4.1 on 2022-11-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroAsociado', '0005_tipoacteconomica_tipodocumento_alter_genero_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='catalogoProfesiones',
            fields=[
                ('idCatalogoProfesiones', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProfesion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'catalogoProfesiones',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='nombreDocumento',
            field=models.CharField(choices=[('DUI', 'DUI'), ('NIT', 'NIT'), ('PARTI', 'PARTIDA DE NACIMIENTO'), ('PASAP', 'PASAPORTE'), ('CARNE', 'CARNE DE RESIDENCIA')], default='DUI', max_length=6),
        ),
    ]
