# Generated by Django 3.0.1 on 2022-11-03 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registroAsociado', '0006_catalogoprofesiones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='beneficiario',
            fields=[
                ('idBeneficiario', models.AutoField(primary_key=True, serialize=False)),
                ('nombreBeneficiario', models.CharField(max_length=50)),
                ('apellidoBeneficiario', models.CharField(max_length=50)),
                ('telBeneficiario', models.CharField(max_length=20)),
                ('edadBeneficiario', models.IntegerField()),
                ('parenscoBeneficiario', models.CharField(choices=[('1', 'MAMÁ'), ('2', 'PAPÁ'), ('3', 'HERMANO/A'), ('4', 'ABUELA/O'), ('5', 'HIJO/A'), ('6', 'TIO/A'), ('7', 'NIETO/A'), ('8', 'SOBRINO'), ('9', 'PRIMA/O')], max_length=2)),
            ],
            options={
                'db_table': 'beneficiario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='catalogoActiEconomica',
            fields=[
                ('idcatalogoActiEconomica', models.AutoField(primary_key=True, serialize=False)),
                ('capacidadPago', models.CharField(max_length=150)),
                ('catalogoProfesiones_idcatalogoProfesiones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroAsociado.catalogoProfesiones')),
                ('tipoActEconomica_idTipoActEconomica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroAsociado.tipoActEconomica')),
            ],
            options={
                'db_table': 'catalogoActiEconomica',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='catalogoDocumentos',
            fields=[
                ('idCatalogoDocumentos', models.AutoField(primary_key=True, serialize=False)),
                ('nunDocumento', models.CharField(max_length=50)),
                ('tipoDocumento_idTipoDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroAsociado.tipoDocumento')),
            ],
            options={
                'db_table': 'catalogoDocumentos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('primerNombre', models.CharField(max_length=45)),
                ('segundoNombre', models.CharField(max_length=45)),
                ('primerApellido', models.CharField(max_length=45)),
                ('segundoApellido', models.CharField(max_length=45)),
                ('apellidoCasada', models.CharField(max_length=45)),
                ('fechaNacimiento', models.CharField(max_length=11)),
                ('nacionalidad', models.CharField(max_length=45)),
                ('paisNacimiento', models.CharField(max_length=45)),
                ('ubicacion', models.CharField(max_length=100)),
                ('subRegion', models.CharField(max_length=50)),
                ('estadoCivil', models.CharField(choices=[('1', 'CASADO'), ('2', 'DIVORCIADO'), ('3', 'VIUDO'), ('4', 'SOLTERO')], max_length=2)),
                ('asociacion_idAsociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroAsociado.asociacion')),
                ('catalogoActiEconomica_idCatalogoActiEconomica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroAsociado.catalogoActiEconomica')),
                ('catalogoDocumentos_idCatalogoDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroAsociado.catalogoDocumentos')),
                ('genero_idGenero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroAsociado.genero')),
            ],
            options={
                'db_table': 'cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='referencias',
            fields=[
                ('idReferenciaCliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombreReferencia', models.CharField(max_length=100)),
                ('telReferencia', models.CharField(max_length=20)),
                ('correoReferencia', models.CharField(max_length=100)),
                ('cliente_idCliente3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroAsociado.cliente')),
            ],
            options={
                'db_table': 'referencias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='catalogoReferencias',
            fields=[
                ('idCatalogoReferencia', models.AutoField(primary_key=True, serialize=False)),
                ('parenscoBeneficiario', models.CharField(choices=[('1', 'PERSONAL'), ('2', 'FAMILIAR')], max_length=2)),
                ('asociaciones', models.CharField(max_length=120)),
                ('cliente_idCliente1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroAsociado.cliente')),
                ('referencias_idReferenciaCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroAsociado.referencias')),
            ],
            options={
                'db_table': 'catalogoReferencias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='catalogoBeneficiario',
            fields=[
                ('idCatalogoBeneficiario', models.AutoField(primary_key=True, serialize=False)),
                ('porcentajeBeneficiario', models.IntegerField()),
                ('beneficiario_idBeneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroAsociado.beneficiario')),
                ('cliente_idCliente2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroAsociado.cliente')),
            ],
            options={
                'db_table': 'catalogoBeneficiario',
                'managed': True,
            },
        ),
    ]
