# Generated by Django 4.1.3 on 2022-11-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroAsociado', '0007_beneficiario_catalogoactieconomica_catalogobeneficiario_catalogodocumentos_catalogoreferencias_clien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumento',
            name='nombreDocumento',
            field=models.CharField(choices=[('DUI', 'DUI'), ('NIT', 'NIT'), ('PARTI', 'PARTIDA DE NACIMIENTO'), ('PASAP', 'PASAPORTE'), ('CARNE', 'CARNE DE RESIDENCIA')], default='DUI', max_length=50),
        ),
    ]
