# Generated by Django 4.1.3 on 2022-11-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroAsociado', '0008_alter_tipodocumento_nombredocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='nombreGenero',
            field=models.CharField(choices=[('H', 'HOMBRE'), ('M', 'MUJER')], max_length=10),
        ),
    ]
