# Generated by Django 4.1.3 on 2022-11-04 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registroAsociado', '0010_alter_genero_nombregenero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='trabajo',
            fields=[
                ('idTrabajo', models.AutoField(primary_key=True, serialize=False)),
                ('capacidadPago', models.CharField(max_length=150)),
                ('catalogoProfesiones_idcatalogoProfesiones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroAsociado.catalogoprofesiones')),
            ],
            options={
                'db_table': 'trabajo',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='asociacion_idAsociado',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='catalogoActiEconomica_idCatalogoActiEconomica',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='catalogoDocumentos_idCatalogoDocumento',
        ),
        migrations.AddField(
            model_name='asociacion',
            name='cliente_idCliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registroAsociado.cliente'),
        ),
        migrations.AddField(
            model_name='catalogodocumentos',
            name='cliente_idCliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registroAsociado.cliente'),
        ),
        migrations.DeleteModel(
            name='catalogoActiEconomica',
        ),
        migrations.AddField(
            model_name='trabajo',
            name='cliente_idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroAsociado.cliente'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='tipoActEconomica_idTipoActEconomica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroAsociado.tipoacteconomica'),
        ),
    ]
