# Generated by Django 4.1.3 on 2022-11-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroAsociado', '0011_trabajo_remove_cliente_asociacion_idasociado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellidoCasada',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
