# Generated by Django 4.1.3 on 2022-11-05 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registroAsociado', '0012_alter_cliente_apellidocasada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogoreferencias',
            name='cliente_idCliente1',
        ),
        migrations.RemoveField(
            model_name='catalogoreferencias',
            name='referencias_idReferenciaCliente',
        ),
        migrations.RenameField(
            model_name='catalogodocumentos',
            old_name='nunDocumento',
            new_name='numDocumento',
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='clienteBeneficiario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registroAsociado.cliente'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='porcentajeBeneficiario',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='referencias',
            name='tipoReferencia',
            field=models.CharField(choices=[('1', 'PERSONAL'), ('2', 'FAMILIAR')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='referencias',
            name='cliente_idCliente3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registroAsociado.cliente'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='cliente_idCliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registroAsociado.cliente'),
        ),
        migrations.DeleteModel(
            name='catalogoBeneficiario',
        ),
        migrations.DeleteModel(
            name='catalogoReferencias',
        ),
    ]
